export enum TYPE_IOCFG {
    FULL_DIGITAL_INPUT = 0,
    FULL_DIGITAL_OUTPUT_HIGH,
    FULL_DIGITAL_OUTPUT_LOW,
    FULL_ANALOG_INPUT,
    INIT
}

export enum TYPE_IO {
    DISABLED,
    NA,
    ANALOG_INPUT = 2,
    DIGITAL_INPUT,
    DIGITAL_OUTPUT_LOW,
    DIGITAL_OUTPUT_HIGH
}

export enum TYPE_MODULE {
    RELAY = 0,
    SENSOR=1
}